### ISSUE TITLE
I got some problems

### ISSUE THREAD

**Issue by NukRockM1033307** [dmn001/steam_review_scraper#1]
can you give me some instructions? thanks!

http://i.imgur.com/di8nlLY.png

Steam already update their reviews system 

maybe you have to update your code :D

**Comment by dmn001** [comment]
Hi, you are using Python 3.0+, but the code requires Python 2.7+.

**Comment by NukRockM1033307** [comment]
So that explains it.
Thank you for your notice!
I will try!
